all : cvrp/HeuristicCVRP.java cvrp/VRPinstance.java cvrp/GiantTour.java cvrp/TestCVRP.java cvrp/Round.java  cvrp/CustomList.java util/Link.java cvrp/MainCVRP.java cvrp/ClarkeWright.java
	javac -Xlint:unchecked $^

clean :
	rm -rf cvrp/*.class
